# Generated by Django 5.1.1 on 2024-10-13 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Tovar nomi')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Tovar narxi')),
                ('discount_percent', models.PositiveSmallIntegerField(verbose_name='Chegirma foizi')),
                ('is_active', models.BooleanField(default=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/')),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
