# Generated by Django 5.1.1 on 2024-10-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='contact_images/'),
        ),
    ]
