# Generated by Django 5.1.1 on 2024-12-05 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
